# Generated by Django 6.0.1 on 2026-03-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupoFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_do_grupo",
                    models.CharField(max_length=50, verbose_name="Grupo do fornecedor"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Grupo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_fornecedor",
                    models.CharField(max_length=200, verbose_name="Razão social"),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail de contato"
                    ),
                ),
                (
                    "foto_grupo_fornecedor",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fornecedores/",
                        verbose_name="Foto Grupo de fornecedor",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição fornecedor"
                    ),
                ),
                (
                    "grupo_fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fornecedores.grupofornecedor",
                        verbose_name="Grupo fornecedor",
                    ),
                ),
            ],
        ),
    ]
