# Generated by Django 6.0.1 on 2026-03-18 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedores",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data da Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fornecedores",
            name="ultima_alteracao",
            field=models.DateTimeField(auto_now=True, verbose_name="Ultima Alteração"),
        ),
    ]
