# Generated by Django 6.0.1 on 2026-03-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0017_produtos_data_criacao_produtos_estoque_and_more"),
        ("fornecedores", "0002_fornecedores_data_criacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_oc",
                    models.PositiveIntegerField(
                        editable=False,
                        unique=True,
                        verbose_name="Número Ordem de Compra",
                    ),
                ),
                (
                    "grupo_fornec",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Grupo do Fornecedor",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                (
                    "preco_produto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço produto",
                    ),
                ),
                ("quantidade", models.FloatField(verbose_name="Quantidade")),
                (
                    "total_oc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total da OC.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "ABERTO"),
                            ("FECHADO", "FECHADO"),
                            ("CANCELADO", "CANCELADO"),
                        ],
                        default="ABERTO",
                        max_length=20,
                        verbose_name="Status da OC.",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descriçao"),
                ),
                (
                    "data_oc",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Ordem de Compra"
                    ),
                ),
                (
                    "fornecedores",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fornecedores.fornecedores",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="balcao.produtos",
                        verbose_name="Nome Produto",
                    ),
                ),
            ],
        ),
    ]
