# Generated by Django 6.0.1 on 2026-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0003_ordemcompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemcompra",
            name="grupo_fornec",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                null=True,
                verbose_name="Grupo do Fornecedor",
            ),
        ),
    ]
