# Generated by Django 6.0.1 on 2026-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0004_alter_ordemcompra_grupo_fornec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemcompra",
            name="total_oc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=10,
                null=True,
                verbose_name="Total da OC.",
            ),
        ),
    ]
