# Generated by Django 6.0.1 on 2026-03-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("balcao", "0017_produtos_data_criacao_produtos_estoque_and_more"),
        ("fornecedores", "0005_alter_ordemcompra_total_oc"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotasEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_ordem",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Data da OC"
                    ),
                ),
                (
                    "grupo_fornec",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        verbose_name="Grupo do Fornecedor",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço unitário"
                    ),
                ),
                ("quantidade", models.FloatField(verbose_name="Quantidade")),
                (
                    "total_nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Nota Fiscal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("FECHADO", "Fechado")],
                        default="FECHADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descriçao"),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Entrada"
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fornecedores.fornecedores",
                        verbose_name="Nome do Fornecedor",
                    ),
                ),
                (
                    "numero_oc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fornecedores.ordemcompra",
                        verbose_name="Número OC",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="balcao.produtos",
                        verbose_name="Produto",
                    ),
                ),
            ],
        ),
    ]
