# Generated by Django 6.0.1 on 2026-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas_fiscais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notasentrada",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Preço unitário",
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="quantidade",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantidade"),
        ),
    ]
