# Generated by Django 6.0.1 on 2026-03-24 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0017_produtos_data_criacao_produtos_estoque_and_more"),
        ("fornecedores", "0005_alter_ordemcompra_total_oc"),
        ("notas_fiscais", "0002_alter_notasentrada_preco_unitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notasentrada",
            name="data_ordem",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da OC"
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="fornecedores.fornecedores",
                verbose_name="Nome do Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="grupo_fornec",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Grupo do Fornecedor"
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="balcao.produtos",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="total_nota",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Nota Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="notasentrada",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidade"
            ),
        ),
    ]
