# Generated by Django 6.0.1 on 2026-03-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas_fiscais", "0003_alter_notasentrada_data_ordem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notasentrada",
            name="numero_nota_entrada",
            field=models.IntegerField(default=91, verbose_name="Numero nota fiscal"),
            preserve_default=False,
        ),
    ]
