# Generated by Django 6.0.1 on 2026-01-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalcaoVendas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_produto", models.CharField(max_length=100)),
                ("tipo_produto", models.CharField(max_length=20)),
                ("quantidade", models.FloatField(max_length=10)),
                ("preco", models.FloatField(max_length=20)),
                ("total", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
