# Generated by Django 6.0.1 on 2026-01-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_produto", models.CharField(max_length=100)),
                ("tipo_produto", models.CharField(max_length=20)),
                ("preco", models.FloatField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="BalcaoVendas",
        ),
    ]
