# Generated by Django 6.0.1 on 2026-01-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0002_produtos_delete_balcaovendas"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendasBalcao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_produto", models.CharField(max_length=200)),
                ("tipo_produto", models.CharField(max_length=20)),
                ("preco", models.FloatField(max_length=20)),
                ("quantidade", models.FloatField(max_length=20)),
                ("total", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
