# Generated by Django 6.0.1 on 2026-01-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0003_vendasbalcao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendasbalcao",
            name="tipo_produto",
        ),
        migrations.AddField(
            model_name="vendasbalcao",
            name="tipo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="vendasbalcao",
            name="nome_produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="balcao.produtos"
            ),
        ),
        migrations.AlterField(
            model_name="vendasbalcao",
            name="preco",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
