# Generated by Django 6.0.1 on 2026-01-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0004_remove_vendasbalcao_tipo_produto_vendasbalcao_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendasbalcao",
            name="tipo",
            field=models.CharField(blank=True, null=True),
        ),
    ]
