# Generated by Django 6.0.1 on 2026-01-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0005_alter_vendasbalcao_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendasbalcao",
            old_name="nome_produto",
            new_name="produto",
        ),
    ]
