# Generated by Django 6.0.1 on 2026-01-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0006_rename_nome_produto_vendasbalcao_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeProduto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_unidade", models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name="produtos",
            name="tipo_produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="balcao.unidadeproduto"
            ),
        ),
    ]
