# Generated by Django 6.0.1 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0007_unidadeproduto_alter_produtos_tipo_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="tipo_produto",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="UnidadeProduto",
        ),
    ]
