# Generated by Django 6.0.1 on 2026-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0008_alter_produtos_tipo_produto_delete_unidadeproduto"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeProduto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_unidade", models.CharField(max_length=5)),
            ],
        ),
    ]
