# Generated by Django 6.0.1 on 2026-01-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0009_unidadeproduto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="tipo_produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="balcao.unidadeproduto"
            ),
        ),
    ]
