# Generated by Django 6.0.1 on 2026-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0010_alter_produtos_tipo_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendasbalcao",
            name="imagem",
            field=models.ImageField(
                blank=True,
                height_field=1080,
                null=True,
                upload_to="produtos/",
                width_field=1920,
            ),
        ),
    ]
