# Generated by Django 6.0.1 on 2026-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0012_alter_vendasbalcao_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendasbalcao",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="balcao/"),
        ),
    ]
