# Generated by Django 6.0.1 on 2026-03-11 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0014_alter_vendasbalcao_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendasbalcao",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="balcao.unidadeproduto",
            ),
        ),
    ]
