# Generated by Django 6.0.1 on 2026-03-11 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0015_alter_vendasbalcao_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendasbalcao",
            old_name="tipo",
            new_name="unidade",
        ),
    ]
