# Generated by Django 6.0.1 on 2026-03-18 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balcao", "0016_rename_tipo_vendasbalcao_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data da Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produtos",
            name="estoque",
            field=models.FloatField(default=0, verbose_name="Estoque Atual"),
        ),
        migrations.AddField(
            model_name="produtos",
            name="ultima_alteracao",
            field=models.DateTimeField(auto_now=True, verbose_name="Ultima Alteração"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço"
            ),
        ),
    ]
